language: android
sudo: required
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-29
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - extra-android-m2repository
jobs:
  include:
    script:
    - chmod +x ./gradlew
    - ./gradlew androidDependencies
    - ./gradlew ktlint
    - ./gradlew lint