name: Android CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: git update-index --chmod=+x gradlew
    - name: Run ktlint
      run: ./gradlew ktlint
    - name: Run detekt
      run: ./gradlew detekt
    - name: Run test
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew build
